apiVersion: batch/v1beta1 #batch/v2alpha1
kind: CronJob
metadata:
  name: job-inspection
spec:
  #schedule: "55 * * * *" # 分钟，小时，日，月，星期
  schedule: "20 9,18 * * *" # 分钟，小时，日，月，星期
  startingDeadlineSeconds: 300 # 300秒没有启动成功，就不再启动
  concurrencyPolicy: Forbid #Allow 允许job并发执行，Forbid只允许当前这个执行，Replace取消当前这个，而执行新的
  suspend: false # 设置为true，后续所有执行被挂起
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 100 # 任务完成后的10s之后自动删除pod，k8s 1.12以后才有
      backoffLimit: 5 # 最大允许失败的次数
      template:
        spec:
          nodeSelector:
            kubernetes.io/hostname: node01
          restartPolicy: OnFailure
          volumes:
            - name: system-info-json
              hostPath:
                path: /tmp/system_info.json
            - name: inspection-log
              hostPath:
                path: /tmp/patrol.log
            - name: dshm
              emptyDir: 
                medium: Memory
            - name: code
              hostPath: 
                path: /root/inspection/code/inspection
          containers:
            - name: inspection-job
              #image: inspection-cron-job:2022011301
              image: inspection-cron-job:2022031702
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: inspection-log
                  mountPath: /tmp/patrol.log
                - name: dshm
                  mountPath: /dev/shm
                - name: code
                  mountPath: /root/inspection
                - name:  system-info-json
                  mountPath: /tmp/system_info.json
              env:
               - name: INSPECTION_DOMAIN # 当前环境的域名后缀
                 value: rootcloud-iot.ag.com
               - name: INSPECTION_USERNAME # 访问根云平台页面的用户名
                 value: dy_test
               - name: INSPECTION_PASSWORD # 访问根云平台页面的密码
                 value: Changeme_123
               - name: INSPECTION_CHECK_URL # 通过页面去检查的url链接地址
                 value: http://rootcloud-console.rootcloud-iot.ag.com/frame-cms/api/device/find?_includeMetadata=true&_limit=3&_skip=0&_sort=%5B%7B%22field%22%3A%20%22created%22%2C%20%22sortType%22%3A%20%22DESC%22%7D%5D
               - name: PLATFORM_ENV_NAME # 环境平台名称,例如 新天钢，长城汽车
                 value: 导远电子
               - name: QIWEI_URL # 企业微信机器人URL
                 #value: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=5053c60e-03bf-4038-ba4f-76b14dde90b1
                 value: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=dffcd79f-8c0c-41e8-a30a-371506d21a26
               - name: GRAFANA_USERNAME
                 value: admin
               - name: GRAFANA_PASSWORD
                 value: strongpassword
               - name: GRAFANA_KAFKA_LAG_DETAIL_URL
                 value: http://grafana.rootcloud-iot.ag.com/d/KZooFzuWk/gong-kuang-shang-chuan-jian-kong-dashboard?viewPanel=108&orgId=1&kiosk=tv&to=now&from=now-
               - name: LAST_TIME
                 value: 24h
               - name: GRAFANA_KAFKA_LAG_DETAIL_URL2
                 value: http://grafana.rootcloud-iot.ag.com/d/KZooFzuWk/gong-kuang-shang-chuan-jian-kong-dashboard?viewPanel=2&orgId=1&kiosk=tv&to=now&from=now-
               - name: LAST_TIME2
                 value: 24h
               - name: ISSEND
                 value: "0"
               - name: INSPECTION_ROOTCLOUD_THING_INSTANCE_URL #物实例在线设备页面地址
                 value: http://rootcloud-console.rootcloud-iot.ag.com/service/cms?path=cms&%24in_app_url=%2Fframe-cms%2Fdevice%2Flegacy%2Fv2-thing-instance%3Ftab%3Ddevice%26value%3D%26dimension%3DFUZZY%26deviceTypeId%3D%26gatewayId%3D%26linkedWay%3D%26selectedStatus%3Donline%26workingStatus%3D%26searchTagValue%3D%255B%255D%26selfReg%3D%26enableSubDevSetGateway%3D%26searchManufacturer%3D%26searchDeviceVersion%3D%26searchFirmwareVersion%3D%26searchHardwareVersion%3D%26selectedDisableAlarmStatus%3D%26page%3D1%26size%3D10
               - name: INSPECTION_WEB_API_URL
                 value: http://10.1.135.2:51221/receive
               - name: ENV_SIMPLE_NAME
                 value: dydz
